#pragma kernel CSMain
#include "Common.hlsl"

StructuredBuffer<Particle> Particles;
RWStructuredBuffer<Chunk> Chunks;
uint ParticlesLength;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    for(uint i = 0; i < ParticlesLength; i++){
        Particle particle = Particles[i];
        int chunkId = particle.chunkId;
        Chunk chunk = Chunks[chunkId];
        if(chunk.particlesStart == -1)
            chunk.particlesStart = i;
        chunk.particlesNum++;
    }
}
